### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by good-engineer** [good-engineer/body-joint-tracking#1]
- [x] Should test UDP sending connection by creating a temporary client 
- [x] Test client in unreal engine
- [x] Add frame rate
- [ ] Change frame rate
- [ ] After receiving beacons should test beacon library (the library currently is not read in the visual studio)
- [ ] Change UDP to multi broadcasting
- [ ] At the end Should test in unreal engine

**Comment by good-engineer** [comment]
The client is created but not tested yet!

**Comment by good-engineer** [comment]
Test client in unreal engine and Add frame rate is done!
